"""add_server_defaults_to_user_timestamps

Revision ID: 13a2695a4eef
Revises: df9eb5ec316d
Create Date: 2025-10-26 11:39:09.250641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '13a2695a4eef'
down_revision: Union[str, Sequence[str], None] = 'df9eb5ec316d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('agent_build_logs_agent_version_id_fkey'), 'agent_build_logs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_build_logs', 'agent_versions', ['agent_version_id'], ['id'])
    op.drop_index(op.f('ix_agent_mcp_bindings_unique'), table_name='agent_mcp_bindings')
    op.create_index(op.f('ix_agent_mcp_bindings_id'), 'agent_mcp_bindings', ['id'], unique=False)
    op.drop_constraint(op.f('agent_test_runs_agent_version_id_fkey'), 'agent_test_runs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_test_runs', 'agent_versions', ['agent_version_id'], ['id'])
    op.drop_constraint(op.f('agent_version_diffs_to_version_id_fkey'), 'agent_version_diffs', type_='foreignkey')
    op.drop_constraint(op.f('agent_version_diffs_from_version_id_fkey'), 'agent_version_diffs', type_='foreignkey')
    op.create_foreign_key(None, 'agent_version_diffs', 'agent_versions', ['to_version_id'], ['id'])
    op.create_foreign_key(None, 'agent_version_diffs', 'agent_versions', ['from_version_id'], ['id'])
    op.drop_constraint(op.f('agent_versions_agent_id_fkey'), 'agent_versions', type_='foreignkey')
    op.create_foreign_key(None, 'agent_versions', 'agents', ['agent_id'], ['id'])
    op.alter_column('agents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(op.f('mcp_server_configs_name_key'), 'mcp_server_configs', type_='unique')
    op.create_index(op.f('ix_mcp_server_configs_id'), 'mcp_server_configs', ['id'], unique=False)
    op.create_index(op.f('ix_mcp_tool_executions_id'), 'mcp_tool_executions', ['id'], unique=False)
    op.drop_constraint(op.f('uq_user_oauth_provider'), 'oauth_accounts', type_='unique')
    op.drop_constraint(op.f('prompt_templates_name_key'), 'prompt_templates', type_='unique')
    op.drop_constraint(op.f('prompt_templates_created_by_fkey'), 'prompt_templates', type_='foreignkey')
    op.create_foreign_key(None, 'prompt_templates', 'users', ['created_by'], ['id'])
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('role_permissions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.drop_constraint(None, 'prompt_templates', type_='foreignkey')
    op.create_foreign_key(op.f('prompt_templates_created_by_fkey'), 'prompt_templates', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_unique_constraint(op.f('prompt_templates_name_key'), 'prompt_templates', ['name'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_user_oauth_provider'), 'oauth_accounts', ['user_id', 'oauth_name'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_mcp_tool_executions_id'), table_name='mcp_tool_executions')
    op.drop_index(op.f('ix_mcp_server_configs_id'), table_name='mcp_server_configs')
    op.create_unique_constraint(op.f('mcp_server_configs_name_key'), 'mcp_server_configs', ['name'], postgresql_nulls_not_distinct=False)
    op.alter_column('conversations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('agents', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'agent_versions', type_='foreignkey')
    op.create_foreign_key(op.f('agent_versions_agent_id_fkey'), 'agent_versions', 'agents', ['agent_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'agent_version_diffs', type_='foreignkey')
    op.drop_constraint(None, 'agent_version_diffs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_version_diffs_from_version_id_fkey'), 'agent_version_diffs', 'agent_versions', ['from_version_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(op.f('agent_version_diffs_to_version_id_fkey'), 'agent_version_diffs', 'agent_versions', ['to_version_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(None, 'agent_test_runs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_test_runs_agent_version_id_fkey'), 'agent_test_runs', 'agent_versions', ['agent_version_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_agent_mcp_bindings_id'), table_name='agent_mcp_bindings')
    op.create_index(op.f('ix_agent_mcp_bindings_unique'), 'agent_mcp_bindings', ['agent_id', 'server_id'], unique=True)
    op.drop_constraint(None, 'agent_build_logs', type_='foreignkey')
    op.create_foreign_key(op.f('agent_build_logs_agent_version_id_fkey'), 'agent_build_logs', 'agent_versions', ['agent_version_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
